<?php
require __DIR__.'/bootstrap.php';
require_permission('marketing.manage');
$pageTitle='ES MULTISERVICIOS Marketing'; $active='marketing';
$message='';$type='success';
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf(); $action=(string)($_POST['action']??'');
 try{
  if($action==='copy'){
   $keys=['hero_kicker','hero_title','hero_text','hero_primary','hero_secondary','solutions_title','solutions_text','izzy_title','izzy_text','cami_title','cami_text','services_title','services_text','affiliate_title','affiliate_text','affiliate_cta','projects_title','why_title','contact_title','contact_text','support_cta'];
   $st=db()->prepare('INSERT INTO landing_content(content_key,lang,content_value) VALUES(?,?,?) ON DUPLICATE KEY UPDATE content_value=VALUES(content_value)');
   foreach(['es','en'] as $lang)foreach($keys as $key)$st->execute([$key,$lang,trim((string)($_POST[$key.'_'.$lang]??''))]);
   log_activity('marketing.copy','Updated bilingual marketing copy'); $message='Bilingual marketing content saved.';
  }elseif($action==='product'){
   $id=(int)($_POST['id']??0);$st=db()->prepare('UPDATE marketing_products SET description_es=?,description_en=?,features_es=?,features_en=?,cta_url=?,sort_order=?,active=? WHERE id=?');
   $st->execute([trim((string)$_POST['description_es']),trim((string)$_POST['description_en']),trim((string)$_POST['features_es']),trim((string)$_POST['features_en']),trim((string)$_POST['cta_url']),(int)$_POST['sort_order'],isset($_POST['active'])?1:0,$id]);$message='Product updated.';
  }elseif($action==='plan_save'){
   $id=(int)($_POST['id']??0);$vals=[trim((string)$_POST['product_key']),trim((string)$_POST['name_es']),trim((string)$_POST['name_en']),trim((string)$_POST['description_es']),trim((string)$_POST['description_en']),trim((string)$_POST['price_label_es']),trim((string)$_POST['price_label_en']),trim((string)$_POST['features_es']),trim((string)$_POST['features_en']),trim((string)$_POST['badge_es']),trim((string)$_POST['badge_en']),trim((string)$_POST['cta_url']),isset($_POST['featured'])?1:0,(int)$_POST['sort_order'],isset($_POST['active'])?1:0];
   if($id){$st=db()->prepare('UPDATE marketing_plans SET product_key=?,name_es=?,name_en=?,description_es=?,description_en=?,price_label_es=?,price_label_en=?,features_es=?,features_en=?,badge_es=?,badge_en=?,cta_url=?,featured=?,sort_order=?,active=? WHERE id=?');$st->execute([...$vals,$id]);}
   else{$st=db()->prepare('INSERT INTO marketing_plans(product_key,name_es,name_en,description_es,description_en,price_label_es,price_label_en,features_es,features_en,badge_es,badge_en,cta_url,featured,sort_order,active) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)');$st->execute($vals);} $message='Plan saved.';
  }elseif($action==='plan_delete'){
   db()->prepare('DELETE FROM marketing_plans WHERE id=?')->execute([(int)$_POST['id']]);$message='Plan deleted.';
  }elseif($action==='project_save'){
   $id=(int)($_POST['id']??0);$vals=[trim((string)$_POST['title']),trim((string)$_POST['category_es']),trim((string)$_POST['category_en']),trim((string)$_POST['description_es']),trim((string)$_POST['description_en']),trim((string)$_POST['project_url']),(int)$_POST['sort_order'],isset($_POST['active'])?1:0];
   if($id){$st=db()->prepare('UPDATE marketing_projects SET title=?,category_es=?,category_en=?,description_es=?,description_en=?,project_url=?,sort_order=?,active=? WHERE id=?');$st->execute([...$vals,$id]);}else{$st=db()->prepare('INSERT INTO marketing_projects(title,category_es,category_en,description_es,description_en,project_url,sort_order,active) VALUES(?,?,?,?,?,?,?,?)');$st->execute($vals);} $message='Project saved.';
  }
 }catch(Throwable $e){$message=$e->getMessage();$type='error';}
}
$copy=['es'=>landing_content('es'),'en'=>landing_content('en')];
$products=db()->query('SELECT * FROM marketing_products ORDER BY sort_order,id')->fetchAll();
$plans=db()->query('SELECT * FROM marketing_plans ORDER BY product_key,sort_order,id')->fetchAll();
$projects=db()->query('SELECT * FROM marketing_projects ORDER BY sort_order,id')->fetchAll();
require __DIR__.'/_header.php';
$keys=['hero_kicker'=>'Hero eyebrow','hero_title'=>'Hero title','hero_text'=>'Hero description','hero_primary'=>'Primary CTA','hero_secondary'=>'WhatsApp CTA','solutions_title'=>'Solutions title','solutions_text'=>'Solutions intro','izzy_title'=>'IZZY title','izzy_text'=>'IZZY intro','cami_title'=>'CAMI title','cami_text'=>'CAMI intro','services_title'=>'Services title','services_text'=>'Services intro','affiliate_title'=>'Affiliate title','affiliate_text'=>'Affiliate description','affiliate_cta'=>'Affiliate CTA','projects_title'=>'Projects title','why_title'=>'Why us title','contact_title'=>'Contact title','contact_text'=>'Contact description','support_cta'=>'Support CTA'];
?>
<div class="page-heading"><div><span class="eyebrow">MARKETING WEBSITE</span><h1>ES MULTISERVICIOS landing page</h1><p>Manage bilingual public content, products, plans and projects without editing code.</p></div><a class="button" href="../?preview=1" target="_blank">Preview website</a></div>
<?php if($message):?><div class="notice <?=$type==='error'?'error':'success'?>"><?=h($message)?></div><?php endif;?>
<div class="admin-marketing-tabs"><a href="#copy">ES / EN content</a><a href="#products">Products</a><a href="#plans">Plans</a><a href="#projects">Projects</a></div>
<section class="panel" id="copy"><div class="panel-head"><div><span class="eyebrow">BILINGUAL CONTENT</span><h2>Public landing copy</h2><p>Spanish and English stay together so the two versions remain consistent.</p></div></div><form method="post"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="copy"><div class="bilingual-grid"><div><h3>Español</h3><?php foreach($keys as $key=>$label):?><label><?=h($label)?><textarea name="<?=h($key)?>_es" rows="<?=$key==='hero_text'||str_contains($key,'text')?3:2?>"><?=h($copy['es'][$key]??'')?></textarea></label><?php endforeach;?></div><div><h3>English</h3><?php foreach($keys as $key=>$label):?><label><?=h($label)?><textarea name="<?=h($key)?>_en" rows="<?=$key==='hero_text'||str_contains($key,'text')?3:2?>"><?=h($copy['en'][$key]??'')?></textarea></label><?php endforeach;?></div></div><button class="button" type="submit">Save bilingual content</button></form></section>
<section class="panel" id="products"><div class="panel-head"><div><span class="eyebrow">PRODUCTS</span><h2>IZZY & CAMI</h2><p>Edit the public description and feature list. Write one feature per line.</p></div></div><div class="marketing-card-grid"><?php foreach($products as $p):?><form class="marketing-card" method="post"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="product"><input type="hidden" name="id" value="<?=$p['id']?>"><div class="marketing-brand-row"><img src="../<?=h($p['logo_path'])?>"><h3><?=h($p['name'])?></h3></div><label>Descripción ES<textarea name="description_es" rows="3"><?=h($p['description_es'])?></textarea></label><label>Description EN<textarea name="description_en" rows="3"><?=h($p['description_en'])?></textarea></label><label>Funciones ES<textarea name="features_es" rows="7"><?=h($p['features_es'])?></textarea></label><label>Features EN<textarea name="features_en" rows="7"><?=h($p['features_en'])?></textarea></label><div class="form-grid"><label>CTA / anchor<input name="cta_url" value="<?=h($p['cta_url'])?>"></label><label>Order<input type="number" name="sort_order" value="<?=$p['sort_order']?>"></label></div><label class="toggle-line"><input type="checkbox" name="active" <?=$p['active']?'checked':''?>> <span>Published</span></label><button class="button" type="submit">Save <?=h($p['name'])?></button></form><?php endforeach;?></div></section>
<section class="panel" id="plans"><div class="panel-head"><div><span class="eyebrow">PLANS</span><h2>Commercial plans</h2><p>The public Plans section appears automatically when at least one active plan exists.</p></div></div><form class="marketing-card plan-editor" method="post"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="plan_save"><input type="hidden" name="id" value="0"><div class="form-grid"><label>Product<select name="product_key"><option value="izzy">IZZY</option><option value="cami">CAMI</option></select></label><label>Order<input type="number" name="sort_order" value="10"></label><label>Name ES<input name="name_es" required></label><label>Name EN<input name="name_en" required></label><label>Price label ES<input name="price_label_es"></label><label>Price label EN<input name="price_label_en"></label><label>Badge ES<input name="badge_es"></label><label>Badge EN<input name="badge_en"></label></div><div class="bilingual-grid"><label>Description ES<textarea name="description_es" rows="3"></textarea></label><label>Description EN<textarea name="description_en" rows="3"></textarea></label><label>Features ES<textarea name="features_es" rows="6" placeholder="One feature per line"></textarea></label><label>Features EN<textarea name="features_en" rows="6" placeholder="One feature per line"></textarea></label></div><label>CTA URL / WhatsApp URL<input name="cta_url"></label><div class="check-row"><label><input type="checkbox" name="featured"> Featured</label><label><input type="checkbox" name="active" checked> Published</label></div><button class="button" type="submit">Add plan</button></form><?php if($plans):?><div class="compact-list"><?php foreach($plans as $p):?><div class="compact-item"><div><strong><?=h($p['name_es'])?></strong><span><?=h(strtoupper($p['product_key']))?> · <?=h($p['price_label_es'])?></span></div><form method="post"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="plan_delete"><input type="hidden" name="id" value="<?=$p['id']?>"><button class="button danger" type="submit">Delete</button></form></div><?php endforeach;?></div><?php endif;?></section>
<section class="panel" id="projects"><div class="panel-head"><div><span class="eyebrow">PROJECTS</span><h2>Projects & case studies</h2></div></div><div class="marketing-card-grid"><?php foreach($projects as $p):?><form class="marketing-card" method="post"><input type="hidden" name="csrf" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="project_save"><input type="hidden" name="id" value="<?=$p['id']?>"><label>Project<input name="title" value="<?=h($p['title'])?>"></label><div class="form-grid"><label>Category ES<input name="category_es" value="<?=h($p['category_es'])?>"></label><label>Category EN<input name="category_en" value="<?=h($p['category_en'])?>"></label></div><label>Description ES<textarea name="description_es" rows="4"><?=h($p['description_es'])?></textarea></label><label>Description EN<textarea name="description_en" rows="4"><?=h($p['description_en'])?></textarea></label><div class="form-grid"><label>Project URL<input name="project_url" value="<?=h($p['project_url'])?>"></label><label>Order<input type="number" name="sort_order" value="<?=$p['sort_order']?>"></label></div><label class="toggle-line"><input type="checkbox" name="active" <?=$p['active']?'checked':''?>> <span>Published</span></label><button class="button" type="submit">Save project</button></form><?php endforeach;?></div></section>
<?php require __DIR__.'/_footer.php'; ?>
